services:
  traefik:
    image: traefik:v3.6
    container_name: traefik-global
    restart: unless-stopped
    command:
      - "--api.dashboard=false"
      - "--api.insecure=true"
      # Enable DEBUG level logging
      - "--log.level=DEBUG"
      # Enable Docker and File providers
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/certs"
      - "--providers.docker.network=traefik"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs:ro
    networks:
      - traefik

networks:
  traefik:
    external: true
    name: traefik
